- hosts: all
  gather_facts: no
  tasks:
    - name: wait for ssh to become available
      local_action: wait_for
                    port=22
                    host="{{ ansible_ssh_host | default(inventory_hostname) }}"
                    search_regex=OpenSSH
                    delay=10

    - name: ensure all hosts are accessible
      local_action: shell ansible -m ping {{ ansible_ssh_host | default(inventory_hostname) }}
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10
